/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.okinkin09.kotlin.cp1.`cp-1`

fun isPrime(num: Int, i: Int = 2): Boolean {
    if (num <= 2) {
        return num == 2
    }
    if (num % i == 0) {
        return false
    }
    if (i * i > num) {
        return true
    }
    return isPrime(num, i + 1)
}

fun main() {
    for (i in 1..100) {
        if (isPrime(i)) {
            println("case #$i: prime number ")
        } else {
            println("case #$i: not a prime number")
        }
    }
}




